### ISSUE TITLE
Project Reorganization

### ISSUE THREAD

**Issue by kayforkaran** [TeamDrag/ProjectDrag#1]
* The files should be organized separately for java-util files, activity java files and xml files, the way it is already in the android studio. I would suggest to push the whole project from the root of the project rather than just the files that you need.
* use ```.gitignore``` for the files that you don't want to be there in the git repository.
* [here](https://help.github.com/articles/ignoring-files/) is a helpful link for ```.gitignore```.

**Comment by kayforkaran** [comment]
I see that you guys have started to distribute it in different folders, which is nice, but I feel it would be simpler if you only push the code from the root of android project directory. Would love to hear your take on that.

**Comment by shivamdhammi** [comment]
# Done 👍
